### ISSUE TITLE
flatten folders

### ISSUE THREAD

**Issue by DavidLeoni** [GabrieleBettini/Homework1#1]
Buondì

ho visto che hai copiato la cartella `TPA-homework1-main` come sotto cartella, ma questo è problematico perchè poi es. ti ritrovi con file .gitignore uno dentro l'altro, e se qualcun'altro vuole riusare il tuo repo è meglio avere una struttura simile.

Quindi cerca di avere una struttura tipo

```
src/
tests/
README.md
```

David

**Comment by GabrieleBettini** [comment]
Ho aperto una pull request, volevo sapere se così andavano bene le cartelle. #2
